### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by theroyakash** [Sam-Bonfire/Practical-Machine-Learning-with-TensorFlow#1]
Can you add some assignment explanations w/solutions. It's gonna be helpful.

**Comment by Sam-Bonfire** [comment]
Actually I've just started the course and this repository is my journey with the same.
I'll be adding them as I complete them

**Comment by theroyakash** [comment]
I just started too. How about collaborating  this repo together?

**Comment by Sam-Bonfire** [comment]
Yeah sure. It's my first time collaborating though. Let's just delete this issue and switch to some other platform for chat.

**Comment by theroyakash** [comment]
What chat platform you got? I’ve got iMessage, E-Mail, WhatsApp and Discord. Don’t use Facebook Messenger (it’s crap)

**Comment by Sam-Bonfire** [comment]
Discord will be good. Send your link.

**Comment by theroyakash** [comment]
![800C4E8D-10C5-4B2D-AE97-448812EF7FBB](https://user-images.githubusercontent.com/43792446/73560636-5a037c00-447d-11ea-86a8-ac8cc58d2c0a.jpeg)
